# Generated by Django 5.1.4 on 2025-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_alter_user_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
